### ISSUE TITLE
IndexError: index 1090 is out of bounds for axis 1 with size 1024

### ISSUE THREAD

**Issue by Binyr** [dylran/crowddiff#23]
Thank you for your code!
**Running command is**:
python cc_utils/preprocess_shtech.py \
    --data_dir datasets/ShanghaiTech2/ \
    --output_dir datasets/ShanghaiTech_processed \
    --dataset part_A_final \
    --mode train \
    --image_size 256 \
    --ndevices 1 \
    --sigma '0.5' \
    --kernel_size '3' \

**Error is** : 
Traceback (most recent call last):
  File "/media/SSD0/byr/Projects/crowdcounting/crowddiff/cc_utils/preprocess_shtech.py", line 401, in <module>
    main(args)
  File "/media/SSD0/byr/Projects/crowdcounting/crowddiff/cc_utils/preprocess_shtech.py", line 129, in main
    density = create_dot_map(locations, image.shape)        
  File "/media/SSD0/byr/Projects/crowdcounting/crowddiff/cc_utils/preprocess_shtech.py", line 224, in create_dot_map
    density[y,x] = 1.
IndexError: index 1090 is out of bounds for axis 1 with size 1024

**Comment by funny000** [comment]
HI@Binyr
can you solve the problem?
what is the problem?
